coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('usuarios/', include('users.urls')),
    path('pedidos/', include('orders.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import MyOrderView

urlpatterns = [
    path('mi-orden/', MyOrderView.as_view(), name="mi-orden"),
]

products/urls.py
from django.urls import path
from .views import ProductFormView, ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name="list-product"),
    path('agregar/', ProductFormView.as_view(), name="add-product")
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView



urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registro/", RegisterView.as_view(), name="register")  
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User

from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):  
        return f"order {self.id} by {self.user}"



class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.order} - {self.product}"

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nombre")
    description = models.TextField(max_length=300, verbose_name="Descripción")  # Cambié 'Description' a minúscula
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio")  # Cambié 'Price' a minúscula
    available = models.BooleanField(default=True, verbose_name="Disponible")  # Cambié 'Available' a minúscula y true a booleano
    photo = models.ImageField(upload_to='logos', null=True, blank=True, verbose_name="Foto")  # Cambié 'Photo' a minúscula

    def __str__(self):  
        return self.name  # Corregí el retorno a 'name', ya que 'description' no existe.

users/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label='Nombre')
    description = forms.CharField(max_length=300, label='Descripción')  # Cambié 'Description' a minúscula
    price = forms.DecimalField(max_digits=10, decimal_places=2, label='Precio')  # Cambié 'Price' a minúscula
    available = forms.BooleanField(initial=True, label='Disponible', required=False)  # Cambié 'Available' a minúscula
    photo = forms.ImageField(label='Foto', required=False)  # Cambié 'Photo' a minúscula

    def save(self):
        Product.objects.create(
            name=self.cleaned_data['name'],
            description=self.cleaned_data['description'],  # Cambié 'Description' a minúscula
            price=self.cleaned_data['price'],  # Cambié 'Price' a minúscula
            available=self.cleaned_data['available'],  # Cambié 'Available' a minúscula
            photo=self.cleaned_data['photo']  # Cambié 'Photo' a minúscula
        )

orders/views.py
from django.shortcuts import render

from django.views.generic import DetailView
# Create your views here.

from .models import Order

class MyOrderView(DetailView):
    model = Order
    template_name = "my_order.html"
    context_object_name = "order"

    def get_object(self, queryset =None):
        return Order.objects.filter(is_active=True ).first()

products/views.py
from django.views import generic
from django.urls import reverse_lazy
from .forms import ProductForm
from .models import Product

class ProductFormView(generic.FormView):
    template_name = "productos.html"
    form_class = ProductForm
    success_url = reverse_lazy('add-product')
 
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
class ProductListView(generic.ListView):
    model = Product
    template_name = 'lista_productos.html'
    context_object_name = 'prodd'

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("login")

orders/templates/my_order.html
{% extends "base.html" %}

{% block content %}

<h1>My Orders</h1>
<p>{{ order.user.username }}</p>
<p>{{ order.order_date }}</p>

{% for product_order in order.orderproduct_set.all %}
<p>{{ product_order.product.name }}</p>
<p>{{ product_order.product.price }}</p>
{% empty %}
<p>No products in this order</p>
{% endfor %}


{% endblock content %}

products/templates/lista_productos.html
{% extends "base.html" %}

{% block content %}


<h1>Lista de productos</h1>

</h1>

<ul>
    {% for product in prodd %}

        {% if product.photo %}
        <a href="#" class="group block overflow-hidden">
            <div class="relative h-[350px] sm:h-[450px]">
              <img
                src="{{product.photo.url}}"
                alt="{{product.name}}"
                class="absolute inset-0 h-full w-full object-cover opacity-100 group-hover:opacity-0"
              />
          
              <img
                src="https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80"
                alt=""
                class="absolute inset-0 h-full w-full object-cover opacity-0 group-hover:opacity-100"
              />
            </div>
            {% endif %}


          
            <div class="relative bg-white pt-3">
              <h3 class="text-sm text-gray-700 group-hover:underline group-hover:underline-offset-4">
                {{ product.name }}
              </h3>
          
              <div class="mt-1.5 flex items-center justify-between text-gray-900">
                <p class="tracking-wide">{{ product.price }}</p>
          
                <p class="text-xs uppercase tracking-wide">6 Colors</p>
              </div>
            </div>
          </a>
    {% endfor %}
</ul>



{% endblock content %}

products/templates/productos.html
<form action="{% url 'add-product' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar</button>
</form>

users/templates/login.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="container mx-auto w-1/3">

<h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar Sesion</h1>

    <form action="" method = "POST">
        {% csrf_token %}    
        {{form|crispy}}
        <button   class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
        type="submit">Login</button>
    </form>

    <p class="text-center text-sm text-gray-500 mt-4">
        ¿No tienes una cuenta?
        <a class="underline" href="{% url "register" %}">Registrate</a>
    </p>

</div>

{% endblock content %}

users/templates/register.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="container mx-auto w-1/3">
    <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar sesión</h1>
    <form action="" method="post" class="my-8">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500" 
            type="submit">
            Registrarse
        </button>
    </form>
    <p class="text-center text-sm text-gray-500 mt-4">
        Ya tienes una cuenta
        <a class="underline" href="{% url "login" %}">Inicia sesión</a>
    </p>
</div>
{% endblock content %}